;;; -*- ti-asm -*-

skDown          = $01
skLeft          = $02
skRight         = $03
skUp            = $04

skEnter         = $09
skAdd           = $0A
skSub           = $0B
skMul           = $0C
skDiv           = $0D
skPower         = $0E
skClear         = $0F

skChs           = $11
sk3             = $12
sk6             = $13
sk9             = $14
skRParen        = $15
skTan           = $16
skVars          = $17

skDecPnt        = $19
sk2             = $1A
sk5             = $1B
sk8             = $1C
skLParen        = $1D
skCos           = $1E
skPrgm          = $1F
skStat          = $20

sk0             = $21
sk1             = $22
sk4             = $23
sk7             = $24
skComma         = $25
skSin           = $26
skApps          = $27
skGraphvar      = $28

skStore         = $2A
skLn            = $2B
skLog           = $2C
skSquare        = $2D
skRecip         = $2E
skMath          = $2F
skAlpha         = $30

skGraph         = $31
skTrace         = $32
skZoom          = $33
skWindow        = $34
skYEqu          = $35
sk2nd           = $36
skMode          = $37
skDel           = $38

skA		= skMath
skB		= skApps
skC		= skPrgm
skD		= skRecip
skE		= skSin
skF		= skCos
skG		= skTan
skH		= skPower
skI		= skSquare
skJ		= skComma
skK		= skLParen
skL		= skRParen
skM		= skDiv
skN		= skLog
skO		= sk7
skP		= sk8
skQ		= sk9
skR		= skMul
skS		= skLn
skT		= sk4
skU		= sk5
skV		= sk6
skW		= skSub
skX		= skStore
skY		= sk1
skZ		= sk2
skSpace		= sk0
