;
;   GetCSC equates
;====================
;
;Author: Texas Instruments
;
;Modifications: -None

skDown          .EQU	01h
skLeft          .EQU	02h
skRight         .EQU	03h
skUp            .EQU	04h
skEnter         .EQU	09h
skAdd           .EQU	0Ah
skSub           .EQU	0Bh
skMul           .EQU	0Ch
skDiv           .EQU	0Dh
skPower         .EQU	0Eh
skClear         .EQU	0Fh
skChs           .EQU	11h
sk3             .EQU	12h
sk6             .EQU	13h
sk9             .EQU	14h
skRParen        .EQU	15h
skTan           .EQU	16h
skVars          .EQU	17h
skDecPnt        .EQU	19h
sk2             .EQU	1Ah
sk5             .EQU	1Bh
sk8             .EQU	1Ch
skLParen        .EQU	1Dh
skCos           .EQU	1Eh
skPrgm          .EQU	1Fh
skStat          .EQU	20h
sk0             .EQU	21h
sk1             .EQU	22h
sk4             .EQU	23h
sk7             .EQU	24h
skComma         .EQU	25h
skSin           .EQU	26h
skMatrix        .EQU	27h
skGraphvar      .EQU	28h
skStore         .EQU	2Ah
skLn            .EQU	2Bh
skLog           .EQU	2Ch
skSquare        .EQU	2Dh
skRecip         .EQU	2Eh
skMath          .EQU	2Fh
skAlpha         .EQU	30h
skGraph         .EQU	31h
skTrace         .EQU	32h
skZoom          .EQU	33h
skWindow        .EQU	34h
skYEqu          .EQU	35h
sk2nd           .EQU	36h
skMode          .EQU	37h
skDel           .EQU	38h